require:
  - rubocop-performance
  - rubocop-rubycw
  - rubocop-rspec

AllCops:
#  DisabledByDefault: true
  Exclude:
    - 'gems/**/*'
  NewCops: enable

Bundler:
  Enabled: true

Gemspec:
  Enabled: true

Lint:
  Enabled: true

Performance:
  Enabled: true

Rubycw:
  Enabled: true

Security:
  Enabled: true

Style/Documentation:
  Enabled: false