require:
  - rubocop-performance
  - rubocop-rubycw
  - rubocop-rspec

AllCops:
#  DisabledByDefault: true
  Exclude:
    - 'vendor/**/*'
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Bundler:
  Enabled: true

Gemspec:
  Enabled: true

Lint:
  Enabled: true

Performance:
  Enabled: true

Rubycw:
  Enabled: true

Security:
  Enabled: true

Style/Documentation:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'