default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: 127.0.0.1

development:
  <<: *default
  database: ruby_knock_development

test:
  <<: *default
  database: ruby_knock_test

production:
  <<: *default
  database: ruby_knock_production
  username: ruby_knock
  password: <%= ENV['RUBY_KNOCK_DATABASE_PASSWORD'] %>
